apiVersion: v1
kind: Secret
metadata:
  name: sassapp-secrets
type: Opaque
stringData:
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_bGVuaWVudC1jb3JhbC00My5jbGVyay5hY2NvdW50cy5kZXYk"
  CLERK_SECRET_KEY: "sk_test_wsq5ynL8LYa5edJfl6FmG7BxMjM1RiBT0oMA9FXSKq"

  NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in"
  NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: "/"
  NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: "/"

  NEXT_PUBLIC_SUPABASE_URL: "https://pgqxprixucdscmskrxvt.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBncXhwcml4dWNkc2Ntc2tyeHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTI4ODgsImV4cCI6MjA2NjMyODg4OH0.NnuH19u9sgiURhL9JeiURUBotD0vpNJdut-sgoWf9qI"

  NEXT_PUBLIC_VAPI_WEB_TOKEN: "e4f8b3de-8fea-4e92-b732-b815ddf2bc60"

  SENTRY_AUTH_TOKEN: "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"
